In [21]:
import pandas as pd
df = pd.read_csv('Dataset/houseprices.csv')

In [22]:
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [ ]:
df.

In [3]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

# Dummy Variable technique

In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv('Dataset/houseprices.csv')
df.head()

town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

In [5]:
merged = pd.concat([df,dummies],axis='columns')
df = merged
df

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [6]:
merged.head()

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [7]:
final = merged.drop(['town','west windsor'],axis = 'columns')

In [8]:
final

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

# One hot encoding technique

In [9]:
df.head()

town  area   price  monroe township  robinsville  west windsor
0  monroe township  2600  550000                1            0             0
1  monroe township  3000  565000                1            0             0
2  monroe township  3200  610000                1            0             0
3  monroe township  3600  680000                1            0             0
4  monroe township  4000  725000                1            0             0

In [10]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()

In [11]:
df_le = df
df_le.town = le.fit_transform(df.town)
df_le

town  area   price  monroe township  robinsville  west windsor
0      0  2600  550000                1            0             0
1      0  3000  565000                1            0             0
2      0  3200  610000                1            0             0
3      0  3600  680000                1            0             0
4      0  4000  725000                1            0             0
5      2  2600  585000                0            0             1
6      2  2800  615000                0            0             1
7      2  3300  650000                0            0             1
8      2  3600  710000                0            0             1
9      1  2600  575000                0            1             0
10     1  2900  600000                0            1             0
11     1  3100  620000                0            1             0
12     1  3600  695000                0            1             0

In [12]:
X = df[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [13]:
y = df[['price']].values
y

array([[550000],
       [565000],
       [610000],
       [680000],
       [725000],
       [585000],
       [615000],
       [650000],
       [710000],
       [575000],
       [600000],
       [620000],
       [695000]], dtype=int64)

In [14]:
from sklearn.preprocessing import OneHotEncoder
ohe  = OneHotEncoder(categories = 'auto')

In [15]:
print(X)

[[   0 2600]
 [   0 3000]
 [   0 3200]
 [   0 3600]
 [   0 4000]
 [   2 2600]
 [   2 2800]
 [   2 3300]
 [   2 3600]
 [   1 2600]
 [   1 2900]
 [   1 3100]
 [   1 3600]]


In [16]:
X = X[:,1:]
X

array([[2600],
       [3000],
       [3200],
       [3600],
       [4000],
       [2600],
       [2800],
       [3300],
       [3600],
       [2600],
       [2900],
       [3100],
       [3600]], dtype=int64)

In [17]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()